export default {
    /*profession */
    REQUEST_PROFESSION_LIST: 'REQUEST_PROFESSION_LIST',
    RECEIVE_PROFESIION_LIST: 'RECEIVE_PROFESIION_LIST',
    FETCH_PROFESSION_LIST_FAIL: 'FETCH_PROFESSION_LIST_FAIL',
    PROFESSION_LIST_PAGE_CHANGE: 'PROFESSION_LIST_PAGE_CHANGE',
    SELECT_PROFESSION_ACTION: 'SELECT_PROFESSION_ACTION',

    /*stories */
    REQUEST_STORIES_LIST: 'REQUEST_STORIES_LIST',
    RECEIVE_STORIES_LIST: 'RECEIVE_STORIES_LIST',
    FETCH_STORIES_LIST_FAIL: 'FETCH_STORIES_LIST_FAIL',
    STORIES_LIST_PAGE_CHANGE: 'STORIES_LIST_PAGE_CHANGE',
    SELECT_STORY_ACTION: 'SELECT_STORY_ACTION',
    /*story specific */
    REQUEST_STORY_SAVE: 'REQUEST_STORY_SAVE',
    STORY_SAVE_FAIL: 'STORY_FAIL_SAVE',
    STORY_SAVE_UPDATE: 'STORY_SAVE_UPDATE', 


    /*path */
    REQUEST_PATH_LIST: 'REQUEST_PATH_LIST',
    RECEIVE_PATH_LIST: 'RECEIVE_PATH_LIST',
    FETCH_PATH_LIST_FAIL: 'FETCH_PATH_LIST_FAIL',
    PATH_LIST_PAGE_CHANGE: 'PATH_LIST_PAGE_CHANGE',

}